services:
  - type: web
    name: hackathon-client
    buildCommand: cd server &&
      bun i &&
      cd ../client &&
      bun i &&
      bun run build
    buildFilter:
      paths:
        - client/**/*
        - server/**/*
    domains:
      - hackvegas.lol
      - 2024.hackvegas.lol
    runtime: static
    envVars:
      - key: VITE_API_URL
        value: 'https://api-2024.hackvegas.lol'
      - key: SKIP_INSTALL_DEPS
        value: 'true'
    headers:
      - path: /*
        name: Content-Security-Policy
        value: "default-src 'self'; script-src 'self' 'unsafe-inline'; img-src 'self' data: *.hackvegas.lol; connect-src 'self' *.hackvegas.lol; object-src 'none'; style-src 'self' 'unsafe-inline' fonts.googleapis.com; font-src 'self' fonts.gstatic.com; frame-ancestors 'none'; upgrade-insecure-requests; block-all-mixed-content"
      - path: /*
        name: Cross-Origin-Embedder-Policy
        value: unsafe-none
      - path: /*
        name: Cross-Origin-Opener-Policy
        value: same-origin
      - path: /*
        name: Cross-Origin-Resource-Policy
        value: same-origin
      - path: /*
        name: Referrer-Policy
        value: no-referrer
      - path: /*
        name: Strict-Transport-Security
        value: max-age=31536000; includeSubDomains; preload
      - path: /*
        name: X-Content-Type-Options
        value: nosniff
      - path: /*
        name: X-Frame-Options
        value: deny
      - path: /**/*.css
        name: Cache-Control
        value: public, max-age=31536000
      - path: /**/*.js
        name: Cache-Control
        value: public, max-age=31536000
      - path: /**/*.html
        name: Cache-Control
        value: public, max-age=86400
      - path: /**/*.png
        name: Cache-Control
        value: public, max-age=31536000
      - path: /**/*.svg
        name: Cache-Control
        value: public, max-age=31536000
      - path: /**/*.webp
        name: Cache-Control
        value: public, max-age=31536000
      - path: /**/*.mp4
        name: Cache-Control
        value: public, max-age=31536000
      - path: /**/*.webm
        name: Cache-Control
        value: public, max-age=31536000
    pullRequestPreviewsEnabled: false
    staticPublishPath: ./client/dist
  - type: web
    runtime: node
    name: hackathon-server
    buildCommand: bun i
    domains:
      - api-2024.hackvegas.lol
    envVars:
      - key: CLIENT_URL
        value: 'https://2024.hackvegas.lol'
    plan: starter
    pullRequestPreviewsEnabled: false
    region: oregon
    rootDir: server
    startCommand: bun start
